### ISSUE TITLE
Corrigir o erro de acessibilidade no preenchimento na área de espaços.

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/theme-MapasCE#2]
### WHY

Essa correção é importante para a facilitar a usabilidade do usuário quando criado e cadastrado o seu espaço no site, precisa estar intuitivo e o checklist deverá funcionar para preenchimento de qual tipo de acessibilidade o espaço terá ou precisará ter.

### HOW

[Desenvolvedor descreva aqui]

### STORY USER

Cenário 1 - Sucesso:

Ao acessar sua conta no site, os usuários interessados em cadastrar um novo espaço podem navegar até a seção “Espaços” no menu de navegação. Na página de espaços, selecionam a opção “Criar Espaço” para iniciar o cadastro, preenchendo informações básicas como nome, tipo de espaço, área de atuação e uma descrição. Após esse preenchimento inicial, os usuários podem optar por “Criar e publicar” o espaço imediatamente ou “Criar em rascunho” para adicionar informações adicionais posteriormente. Em ambos os casos, será apresentada uma página com as informações a serem divulgadas, incluindo detalhes de acessibilidade como a disponibilidade de rampas, banheiros adaptados e vagas preferenciais. Essa seção contará com uma lista de verificação, permitindo aos usuários marcar as facilidades de acessibilidade disponíveis no espaço cadastrado.

Cenário 2 - Insucesso:

Ao tentar cadastrar um novo espaço no site, o usuário segue até a seção "Espaços" e clica em "Criar Espaço", preenchendo as informações básicas requeridas, como nome, tipo de espaço, área de atuação e descrição. No entanto, ao chegar à etapa crucial de detalhar a acessibilidade do espaço, o usuário encontra dificuldades significativas. A página para adicionar informações de acessibilidade, que deve incluir opções como rampas, banheiros adaptados e vagas preferenciais, não carrega adequadamente, ou as caixas de checklist para selecionar as facilidades disponíveis não respondem. Este problema técnico impede o usuário de completar o cadastro do espaço com as informações de acessibilidade necessárias. Como resultado, espaços potencialmente acessíveis não são adequadamente divulgados quanto à sua acessibilidade, dificultando o acesso de pessoas com necessidades especiais e limitando a utilidade do site tanto para quem cadastra quanto para quem busca espaços inclusivos.

Segue exemplo:

### ADDITIONAL INFO

![Image](https://github.com/secultce/mapacultural/assets/13440490/483c0b4b-98ef-49d5-a84c-734e76e35556)

URL Espaços: [Espaços](https://redesign.testes.map.as/espacos/#list](https://redesign.testes.map.as/espacos/#list "‌")

### CHECKLIST

- [x] Remover caixas de checklist múltiplas e redundantes
- [x] Implementar uma única caixa de checklist para cada item de acessibilidade física.
- [x] Redesenhar a seção de acessibilidade para exibir claramente cada item de acessibilidade com uma única caixa de seleção correspondente.

**Comment by Junior-Shyko** [comment]
@alessandrofeitoza O ômi é uma.maquina

**Comment by TalysonSoares** [comment]
https://github.com/secultce/theme-MapasCE/pull/3
